"""initial schema

Revision ID: 4ff093e59f74
Revises: 
Create Date: 2026-08-31 10:53:44.240242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff093e59f74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'account_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('account', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('account_type', 'type_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('account_type', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_log', 'table_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_log', 'operation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_log', 'changed_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('beneficiary', 'beneficiary_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('beneficiary', 'account_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('beneficiary', 'ifsc_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('beneficiary', 'nickname',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('beneficiary', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('branch', 'branch_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('branch', 'ifsc_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('branch', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('branch', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('branch', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('branch', 'contact_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('card', 'card_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('card', 'expiry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('card', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('card_type', 'type_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('card_type', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customer', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customer', 'mobile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customer', 'occupation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customer', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer_address', 'type_of_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer_address', 'address_line',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer_address', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer_address', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customer_address', 'pincode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_customer_address_type'), 'customer_address', type_='unique')
    op.alter_column('employee', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_mobile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.drop_constraint(op.f('employee_employee_status_check'), 'employee', type_='check')
    op.create_check_constraint('employee_status_check', 'employee', "employee_status IN ('ACTIVE','ONLEAVE','RESIGNED')")
    op.alter_column('kyc', 'document_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('kyc', 'document_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('kyc', 'kyc_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'SUCCESS'::text"))
    op.alter_column('kyc', 'verification_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('kyc_document_type_document_number_key'), 'kyc', type_='unique')
    op.create_unique_constraint(None, 'kyc', ['document_number'])
    op.drop_constraint(op.f('kyc_kyc_status_check'), 'kyc', type_='check')
    op.create_check_constraint('kyc_status_check', 'kyc', "kyc_status IN ('VERIFIED','REJECTED','EXPIRED','PENDING')")
    op.alter_column('loan', 'loan_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('loan', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('loan', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('loan_collateral', 'collateral_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('loan_collateral', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('loan_collateral', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('loan_payment', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('loan_payment', 'payment_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.drop_constraint(op.f('loan_payment_payment_amount_check'), 'loan_payment', type_='check')
    op.drop_constraint(op.f('loan_payment_payment_status_check'), 'loan_payment', type_='check')
    op.drop_constraint(op.f('loan_payment_remaining_balance_check'), 'loan_payment', type_='check')
    op.create_check_constraint('loan_payment_status_check', 'loan_payment', "payment_status IN ('PENDING','PAID','OVERDUE')")
    op.create_check_constraint('remaining_balance_status_check', 'loan_payment', 'remaining_balance >=0')
    op.alter_column('support_ticket', 'ticket_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('support_ticket', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('support_ticket', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('support_ticket', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::text"))
    op.alter_column('support_ticket', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::text"))
    op.alter_column('transaction', 'transaction_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transaction', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transaction', 'reference_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transaction', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('transaction_transaction_type_check'), 'transaction', type_='check')
    op.alter_column('transaction_entry', 'entry_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('transaction_entry_entry_type_check'), 'transaction_entry', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('transaction_entry_entry_type_check'), 'transaction_entry', "entry_type = ANY (ARRAY['CREDIT'::text, 'DEBIT'::text])")
    op.alter_column('transaction_entry', 'entry_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_check_constraint(op.f('transaction_transaction_type_check'), 'transaction', "transaction_type = ANY (ARRAY['TRANSFER'::text, 'DEPOSIT'::text, 'WITHDRAWAL'::text, 'PAYMENT'::text])")
    op.alter_column('transaction', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transaction', 'reference_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transaction', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transaction', 'transaction_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('support_ticket', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::text"))
    op.alter_column('support_ticket', 'priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::text"))
    op.alter_column('support_ticket', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('support_ticket', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('support_ticket', 'ticket_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('remaining_balance_status_check', 'loan_payment', type_='check')
    op.drop_constraint('loan_payment_status_check', 'loan_payment', type_='check')
    op.create_check_constraint(op.f('loan_payment_remaining_balance_check'), 'loan_payment', 'remaining_balance >= 0::numeric')
    op.create_check_constraint(op.f('loan_payment_payment_status_check'), 'loan_payment', "payment_status = ANY (ARRAY['PENDING'::text, 'PAID'::text, 'OVERDUE'::text])")
    op.create_check_constraint(op.f('loan_payment_payment_amount_check'), 'loan_payment', 'payment_amount > 0::numeric')
    op.alter_column('loan_payment', 'payment_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('loan_payment', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('loan_collateral', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('loan_collateral', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('loan_collateral', 'collateral_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('loan', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('loan', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('loan', 'loan_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('kyc_status_check', 'kyc', type_='check')
    op.create_check_constraint(op.f('kyc_kyc_status_check'), 'kyc', "kyc_status = ANY (ARRAY['VERIFIED'::text, 'PENDING'::text, 'REJECTED'::text, 'EXPIRED'::text])")
    op.drop_constraint(None, 'kyc', type_='unique')
    op.create_unique_constraint(op.f('kyc_document_type_document_number_key'), 'kyc', ['document_type', 'document_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('kyc', 'verification_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('kyc', 'kyc_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'SUCCESS'::text"))
    op.alter_column('kyc', 'document_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('kyc', 'document_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('employee_status_check', 'employee', type_='check')
    op.create_check_constraint(op.f('employee_employee_status_check'), 'employee', "employee_status = ANY (ARRAY['RESIGNED'::text, 'ACTIVE'::text, 'ONLEAVE'::text])")
    op.alter_column('employee', 'employee_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('employee', 'employee_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_mobile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('employee', 'employee_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_customer_address_type'), 'customer_address', ['customer_id', 'type_of_address'], postgresql_nulls_not_distinct=False)
    op.alter_column('customer_address', 'pincode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer_address', 'state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer_address', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer_address', 'address_line',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer_address', 'type_of_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer', 'occupation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer', 'mobile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customer', 'gender',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('card_type', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('card_type', 'type_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('card', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('card', 'expiry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('card', 'card_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('branch', 'contact_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('branch', 'state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('branch', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('branch', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('branch', 'ifsc_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('branch', 'branch_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('beneficiary', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('beneficiary', 'nickname',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('beneficiary', 'ifsc_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('beneficiary', 'account_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('beneficiary', 'beneficiary_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_log', 'changed_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_log', 'operation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_log', 'table_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('account_type', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account_type', 'type_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('account', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('account', 'account_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
