"""added testing column

Revision ID: 7e2e772c619e
Revises: 4ff093e59f74
Create Date: 2026-08-31 11:10:48.693250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2e772c619e'
down_revision: Union[str, Sequence[str], None] = '4ff093e59f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('aadhar_number', sa.String(length=12), nullable=True))
    op.create_unique_constraint("customer_aadhar_number_key", 'customer', ['aadhar_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("customer_aadhar_number_key", 'customer', type_='unique')
    op.drop_column('customer', 'aadhar_number')
    # ### end Alembic commands ###
